export default [
  {
    id: 1,
    quantity: 87,
    category: "Вытяжное устройство",
    model: "G2H",
    price: 12644,
    minPrice: 6848,
    maxPrice: 56584,
    code: "G2H1065",
    description:
      "Многофункциональное вытяжное устройство для естественной и гибридной вентиляции",
    characteristics: {
      squareMin: 12,
      squareMax: 72,
      circulation: 168,
      isGidro: true,
      isSensor: true,
    },
    image: "G2H",
  },
  {
    id: 2,
    quantity: 5,
    category: "Вытяжное устройство",
    model: "ВХС",
    minPrice: 6848,
    maxPrice: 56584,
    price: 25288,
    code: "G2H1065",
    description: "Вытяжное устройство для механической системы вентиляции",
    characteristics: {
      squareMin: 12,
      squareMax: 72,
      circulation: 168,
      isGidro: true,
      isSensor: true,
    },
    image: "BXC",
  },
  {
    id: 3,
    quantity: 3,
    category: "Вытяжное устройство",
    model: "GHN",
    minPrice: 6848,
    maxPrice: 56584,
    price: 12644,
    code: "G2H1065",
    description: "Вытяжное устройство с датчиком присутствия",
    characteristics: {
      squareMin: 12,
      squareMax: 72,
      circulation: 168,
      isGidro: true,
      isSensor: true,
    },
    image: "GHN",
  },
  {
    id: 4,
    quantity: 11,
    category: "Вытяжное устройство",
    model: "G2H5",
    minPrice: 6848,
    maxPrice: 56584,
    price: 13644,
    code: "G2H1065",
    description: "Вытяжное устройство с датчиком присутствия",
    characteristics: {
      squareMin: 12,
      squareMax: 72,
      circulation: 168,
      isGidro: true,
      isSensor: true,
    },
    image: "G2H",
  },
  {
    id: 5,
    quantity: 2,
    category: "Вытяжное устройство",
    model: "G2H1",
    minPrice: 6848,
    maxPrice: 56584,
    price: 11644,
    code: "G2H1065",
    description: "Вытяжное устройство с датчиком присутствия",
    characteristics: {
      squareMin: 12,
      squareMax: 72,
      circulation: 168,
      isGidro: true,
      isSensor: true,
    },
    image: "G2H",
  },
  {
    id: 6,
    quantity: 87,
    category: "Вытяжное устройство",
    model: "G2H3",
    minPrice: 6848,
    maxPrice: 56584,
    price: 112644,
    code: "G2H1065",
    description: "Вытяжное устройство с датчиком присутствия",
    characteristics: {
      squareMin: 12,
      squareMax: 72,
      circulation: 168,
      isGidro: true,
      isSensor: true,
    },
    image: "G2H",
  },
  {
    id: 7,
    quantity: 187,
    category: "Вытяжное устройство",
    model: "G2H11",
    minPrice: 6848,
    maxPrice: 56584,
    price: 2644,
    code: "G2H1065",
    description: "Вытяжное устройство с датчиком присутствия",
    characteristics: {
      squareMin: 12,
      squareMax: 72,
      circulation: 168,
      isGidro: true,
      isSensor: true,
    },
    image: "G2H",
  },
  {
    id: 8,
    quantity: 87,
    category: "Вытяжное устройство",
    model: "G2H111",
    minPrice: 6848,
    maxPrice: 56584,
    price: 644,
    code: "G2H1065",
    description: "Вытяжное устройство с датчиком присутствия",
    characteristics: {
      squareMin: 12,
      squareMax: 72,
      circulation: 168,
      isGidro: true,
      isSensor: true,
    },
    image: "G2H",
  },
  {
    id: 9,
    quantity: 87,
    category: "Вытяжное устройство",
    model: "G23",
    minPrice: 6848,
    maxPrice: 56584,
    price: 16644,
    code: "G2H1065",
    description: "Вытяжное устройство с датчиком присутствия",
    characteristics: {
      squareMin: 12,
      squareMax: 72,
      circulation: 168,
      isGidro: true,
      isSensor: true,
    },
    image: "G2H",
  },
  {
    id: 10,
    quantity: 87,
    category: "Вытяжное устройство",
    model: "2H",
    minPrice: 6848,
    maxPrice: 56584,
    price: 12644,
    code: "G2H1065",
    description: "Вытяжное устройство с датчиком присутствия",
    characteristics: {
      squareMin: 12,
      squareMax: 72,
      circulation: 168,
      isGidro: true,
      isSensor: true,
    },
    image: "G2H",
  },
];
